In [3]:
import pandas as pd
pd.read_csv("//Users//shrish//Downloads//wine+quality//winequality-white.csv",sep=';')

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
...,...,...,...,...,...,...,...,...,...,...,...,...
4893,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6
4894,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5
4895,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6
4896,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7
4897,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6

In [4]:
from sklearn.model_selection import train_test_split
train , test = train_test_split(pd.read_csv("//Users//shrish//Downloads//wine+quality//winequality-white.csv",sep=';'))

In [5]:
train

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
2778,7.6,0.39,0.32,3.60,0.035,22.0,93.0,0.99144,3.08,0.60,12.5,7
1379,6.9,0.46,0.20,0.90,0.054,5.0,126.0,0.99200,3.10,0.42,10.4,6
1504,7.0,0.17,0.74,12.80,0.045,24.0,126.0,0.99420,3.26,0.38,12.2,8
3111,6.5,0.23,0.39,1.90,0.036,41.0,98.0,0.99000,3.19,0.43,11.9,7
704,5.6,0.25,0.26,3.60,0.037,18.0,115.0,0.99040,3.42,0.50,12.6,6
...,...,...,...,...,...,...,...,...,...,...,...,...
1259,6.2,0.21,0.38,6.80,0.036,64.0,245.0,0.99510,3.06,0.36,9.3,6
3721,7.7,0.30,0.23,2.00,0.068,28.0,138.0,0.99382,3.11,0.62,9.8,5
2807,7.5,0.18,0.72,9.60,0.039,53.0,151.0,0.99802,3.03,0.46,8.9,5
1782,8.5,0.21,0.26,9.25,0.034,73.0,142.0,0.99450,3.05,0.37,11.4,6
40,6.7,0.23,0.39,2.50,0.172,63.0,158.0,0.99370,3.11,0.36,9.4,6

In [6]:
test

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
2668,9.6,0.655,0.21,2.00,0.039,21.0,120.0,0.99188,3.00,1.00,12.6,6
1727,7.6,0.445,0.44,14.50,0.045,68.0,212.0,0.99860,3.48,0.36,10.0,6
2366,7.4,0.330,0.44,7.60,0.050,40.0,227.0,0.99679,3.12,0.52,9.0,5
2949,6.0,0.280,0.52,5.00,0.078,30.0,139.0,0.99494,3.10,0.36,9.0,6
945,6.7,0.150,0.29,5.00,0.058,28.0,105.0,0.99460,3.52,0.44,10.2,7
...,...,...,...,...,...,...,...,...,...,...,...,...
2282,7.4,0.330,0.26,15.60,0.049,67.0,210.0,0.99907,3.06,0.68,9.5,5
4408,5.7,0.290,0.16,7.90,0.044,48.0,197.0,0.99512,3.21,0.36,9.4,5
2631,6.7,0.280,0.28,2.40,0.012,36.0,100.0,0.99064,3.26,0.39,11.7,7
1210,9.2,0.280,0.41,1.00,0.042,14.0,59.0,0.99220,2.96,0.25,10.5,6
111,7.2,0.270,0.46,18.75,0.052,45.0,255.0,1.00000,3.04,0.52,8.9,5